### ISSUE TITLE
We need to take a #mozwow group selfie using foodcam 

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [wkearn/WOW-Boston-Github#17]
The selfie would show up here and we can all retweet it after #mozwow! 
@medialabfoodcam

The live feed is here: 
http://foodcam.media.mit.edu/view/view.shtml

**Comment by wkearn** [comment]
Picture taken!

**Comment by wkearn** [comment]
Picture tweeted!

https://twitter.com/KMMoerman/status/893487724338065408
