### ISSUE TITLE
Less fire alarms, please

### ISSUE THREAD

**Issue by abbycabs** [wkearn/WOW-Boston-Github#3]
Thanks you 🔥 🔥 🚒 👩‍🚒

**Comment by abbycabs** [comment]
Will can
- [ ] find the contractor that accidentally pulled the alarm
- [ ] tell him not to do that

**Comment by Adam-Shire-WIT** [comment]
- [ ] 

- [ ]

**Comment by Adam-Shire-WIT** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by Adam-Shire-WIT** [comment]
- [ ] you need text

- [ ]

**Comment by Kevin-Mattheus-Moerman** [comment]
I can take care this

**Comment by jvallera** [comment]
- [ ] popcorn
- [ ] watermelon juice
- [ ] projector
- [ ] planet earth

**Comment by kevin-fang** [comment]
- [x] :smile:

**Comment by Kevin-Mattheus-Moerman** [comment]
This morning's fire alarm was brought to you by a contractor who mistakenly took the pull station for a light switch in Bartos Theater.

**Comment by Kevin-Mattheus-Moerman** [comment]
Issue is resolved

**Comment by wkearn** [comment]
Are we sure?
